chore: introduce storybook
mnindrazaka/tmdb pull request #11
Opened 2022-02-22 12:26 UTC by AndriP8

2022-02-25 23:54 UTC, mnindrazaka requested changes

2022-02-25 23:54 UTC, mnindrazaka commented on package.json
> +    "build-storybook": "build-storybook"
kalau command build nya diganti aja gimana ? biar seragam sama yang lain, dipisahin pake `:`

```suggestion
    "storybook:build": "build-storybook"
```

2022-02-26 00:06 UTC, AndriP8 commented on package.json
> +    "build-storybook": "build-storybook"
okee, kayaknya emang lebih baik dipisah pake `:`

2022-02-26 01:31 UTC, mnindrazaka approved these changes

2022-02-26 01:31 UTC, merged